name: CI/CD - Currency Converter API

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:  # <- Definimos aqui suas variáveis de ambiente
      EXCHANGE_API_KEY: ${{ secrets.exchange_api_key }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.3'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests with coverage
      run: |
        pytest --cov=app --cov-report=term-missing tests/

    - name: Upload coverage report (optional)
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: htmlcov/
